name: "blogapi"

services:
  database:
    image: postgres:16-alpine
    container_name: blog-database
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
    volumes:
      - blog-database:/var/lib/postgresql/data


volumes:
  blog-database:
